ALTER TABLE products
ADD COLUMN IF NOT EXISTS is_ghost_drop BOOLEAN DEFAULT FALSE;
ALTER TABLE products
ADD COLUMN IF NOT EXISTS ghost_lat DECIMAL(10, 8);
ALTER TABLE products
ADD COLUMN IF NOT EXISTS ghost_lng DECIMAL(11, 8);
ALTER TABLE products
ADD COLUMN IF NOT EXISTS ghost_radius INTEGER DEFAULT 50;
ALTER TABLE products
ADD COLUMN IF NOT EXISTS ghost_clue TEXT;